- id: '1670770197664'
  alias: Cosmin leaving the home
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.cosmin_rusu
      zone_entity: zone.home
      notify_device: d46eeb7d783e7c0bb64171153e834b32
- id: '1671223982043'
  alias: New Automation
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: all
  mode: single
